#Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.cache = true
org.gradle.configuration-cache=true

mod_id=mcea
display_name=Minecraft Comes Epicly Alive
license=MIT
group_id=net.forixaim
authors=Forixaim
issue_tracker=https://github.com/Forixaim/Battle-Arts-API/issues
source_code=https://github.com/Forixaim/Battle-Arts-API
display_url=https://github.com/Forixaim/Battle-Arts-API
credits="Me"
description=An official addon for Epic Fight, Minecraft Comes Epicly Alive is an addon that primarily focuses on adding Epic Fight Integration with MCA: Reborn. For 1.21.1 NeoForged only, with backports allowed by other developers.
